export const getCountryAlphaTwo = alphaThree => {
    // get country record
    const country = country_list.filter(record => record.alpha_three === alphaThree)[0];
    // return alpha two in lower case
    return country.alpha_two.toLowerCase();
}

const country_list = [
    {'country': 'Afghanistan', 'alpha_two': 'AF', 'alpha_three': 'AFG'},
    {'country': 'Albania', 'alpha_two': 'AL', 'alpha_three': 'ALB'},
    {'country': 'Algeria', 'alpha_two': 'DZ', 'alpha_three': 'DZA'},
    {'country': 'American Samoa', 'alpha_two': 'AS', 'alpha_three': 'ASM'},
    {'country': 'Andorra', 'alpha_two': 'AD', 'alpha_three': 'AND'},
    {'country': 'Angola', 'alpha_two': 'AO', 'alpha_three': 'AGO'},
    {'country': 'Anguilla', 'alpha_two': 'AI', 'alpha_three': 'AIA'},
    {'country': 'Antarctica', 'alpha_two': 'AQ', 'alpha_three': 'ATA'},
    {'country': 'Antigua and Barbuda', 'alpha_two': 'AG', 'alpha_three': 'ATG'},
    {'country': 'Argentina', 'alpha_two': 'AR', 'alpha_three': 'ARG'},
    {'country': 'Armenia', 'alpha_two': 'AM', 'alpha_three': 'ARM'},
    {'country': 'Aruba', 'alpha_two': 'AW', 'alpha_three': 'ABW'},
    {'country': 'Australia', 'alpha_two': 'AU', 'alpha_three': 'AUS'},
    {'country': 'Austria', 'alpha_two': 'AT', 'alpha_three': 'AUT'},
    {'country': 'Azerbaijan', 'alpha_two': 'AZ', 'alpha_three': 'AZE'},
    {'country': 'Bahamas', 'alpha_two': 'BS', 'alpha_three': 'BHS'},
    {'country': 'Bahrain', 'alpha_two': 'BH', 'alpha_three': 'BHR'},
    {'country': 'Bangladesh', 'alpha_two': 'BD', 'alpha_three': 'BGD'},
    {'country': 'Barbados', 'alpha_two': 'BB', 'alpha_three': 'BRB'},
    {'country': 'Belarus', 'alpha_two': 'BY', 'alpha_three': 'BLR'},
    {'country': 'Belgium', 'alpha_two': 'BE', 'alpha_three': 'BEL'},
    {'country': 'Belize', 'alpha_two': 'BZ', 'alpha_three': 'BLZ'},
    {'country': 'Benin', 'alpha_two': 'BJ', 'alpha_three': 'BEN'},
    {'country': 'Bermuda', 'alpha_two': 'BM', 'alpha_three': 'BMU'},
    {'country': 'Bhutan', 'alpha_two': 'BT', 'alpha_three': 'BTN'},
    {'country': 'Bolivia', 'alpha_two': 'Plurinational State of', 'alpha_three': 'BO'},
    {'country': 'Bolivia', 'alpha_two': 'BO', 'alpha_three': 'BOL'},
    {'country': 'Bosnia and Herzegovina', 'alpha_two': 'BA', 'alpha_three': 'BIH'},
    {'country': 'Botswana', 'alpha_two': 'BW', 'alpha_three': 'BWA'},
    {'country': 'Bouvet Island', 'alpha_two': 'BV', 'alpha_three': 'BVT'},
    {'country': 'Brazil', 'alpha_two': 'BR', 'alpha_three': 'BRA'},
    {'country': 'British Indian Ocean Territory', 'alpha_two': 'IO', 'alpha_three': 'IOT'},
    {'country': 'Brunei Darussalam', 'alpha_two': 'BN', 'alpha_three': 'BRN'},
    {'country': 'Brunei', 'alpha_two': 'BN', 'alpha_three': 'BRN'},
    {'country': 'Bulgaria', 'alpha_two': 'BG', 'alpha_three': 'BGR'},
    {'country': 'Burkina Faso', 'alpha_two': 'BF', 'alpha_three': 'BFA'},
    {'country': 'Burundi', 'alpha_two': 'BI', 'alpha_three': 'BDI'},
    {'country': 'Cambodia', 'alpha_two': 'KH', 'alpha_three': 'KHM'},
    {'country': 'Cameroon', 'alpha_two': 'CM', 'alpha_three': 'CMR'},
    {'country': 'Canada', 'alpha_two': 'CA', 'alpha_three': 'CAN'},
    {'country': 'Cape Verde', 'alpha_two': 'CV', 'alpha_three': 'CPV'},
    {'country': 'Cayman Islands', 'alpha_two': 'KY', 'alpha_three': 'CYM'},
    {'country': 'Central African Republic', 'alpha_two': 'CF', 'alpha_three': 'CAF'},
    {'country': 'Chad', 'alpha_two': 'TD', 'alpha_three': 'TCD'},
    {'country': 'Chile', 'alpha_two': 'CL', 'alpha_three': 'CHL'},
    {'country': 'China', 'alpha_two': 'CN', 'alpha_three': 'CHN'},
    {'country': 'Christmas Island', 'alpha_two': 'CX', 'alpha_three': 'CXR'},
    {'country': 'Cocos (Keeling) Islands', 'alpha_two': 'CC', 'alpha_three': 'CCK'},
    {'country': 'Colombia', 'alpha_two': 'CO', 'alpha_three': 'COL'},
    {'country': 'Comoros', 'alpha_two': 'KM', 'alpha_three': 'COM'},
    {'country': 'Congo', 'alpha_two': 'CG', 'alpha_three': 'COG'},
    {'country': 'Congo', 'alpha_two': 'the Democratic Republic of the', 'alpha_three': 'CD'},
    {'country': 'Cook Islands', 'alpha_two': 'CK', 'alpha_three': 'COK'},
    {'country': 'Costa Rica', 'alpha_two': 'CR', 'alpha_three': 'CRI'},
    {'country': "Côte d'Ivoire", 'alpha_two': 'CI', 'alpha_three': 'CIV'},
    {'country': 'Ivory Coast', 'alpha_two': 'CI', 'alpha_three': 'CIV'},
    {'country': 'Croatia', 'alpha_two': 'HR', 'alpha_three': 'HRV'},
    {'country': 'Cuba', 'alpha_two': 'CU', 'alpha_three': 'CUB'},
    {'country': 'Cyprus', 'alpha_two': 'CY', 'alpha_three': 'CYP'},
    {'country': 'Czech Republic', 'alpha_two': 'CZ', 'alpha_three': 'CZE'},
    {'country': 'Denmark', 'alpha_two': 'DK', 'alpha_three': 'DNK'},
    {'country': 'Djibouti', 'alpha_two': 'DJ', 'alpha_three': 'DJI'},
    {'country': 'Dominica', 'alpha_two': 'DM', 'alpha_three': 'DMA'},
    {'country': 'Dominican Republic', 'alpha_two': 'DO', 'alpha_three': 'DOM'},
    {'country': 'Ecuador', 'alpha_two': 'EC', 'alpha_three': 'ECU'},
    {'country': 'Egypt', 'alpha_two': 'EG', 'alpha_three': 'EGY'},
    {'country': 'El Salvador', 'alpha_two': 'SV', 'alpha_three': 'SLV'},
    {'country': 'Equatorial Guinea', 'alpha_two': 'GQ', 'alpha_three': 'GNQ'},
    {'country': 'Eritrea', 'alpha_two': 'ER', 'alpha_three': 'ERI'},
    {'country': 'Estonia', 'alpha_two': 'EE', 'alpha_three': 'EST'},
    {'country': 'Ethiopia', 'alpha_two': 'ET', 'alpha_three': 'ETH'},
    {'country': 'Falkland Islands (Malvinas)', 'alpha_two': 'FK', 'alpha_three': 'FLK'},
    {'country': 'Faroe Islands', 'alpha_two': 'FO', 'alpha_three': 'FRO'},
    {'country': 'Fiji', 'alpha_two': 'FJ', 'alpha_three': 'FJI'},
    {'country': 'Finland', 'alpha_two': 'FI', 'alpha_three': 'FIN'},
    {'country': 'France', 'alpha_two': 'FR', 'alpha_three': 'FRA'},
    {'country': 'French Guiana', 'alpha_two': 'GF', 'alpha_three': 'GUF'},
    {'country': 'French Polynesia', 'alpha_two': 'PF', 'alpha_three': 'PYF'},
    {'country': 'French Southern Territories', 'alpha_two': 'TF', 'alpha_three': 'ATF'},
    {'country': 'Gabon', 'alpha_two': 'GA', 'alpha_three': 'GAB'},
    {'country': 'Gambia', 'alpha_two': 'GM', 'alpha_three': 'GMB'},
    {'country': 'Georgia', 'alpha_two': 'GE', 'alpha_three': 'GEO'},
    {'country': 'Germany', 'alpha_two': 'DE', 'alpha_three': 'DEU'},
    {'country': 'Ghana', 'alpha_two': 'GH', 'alpha_three': 'GHA'},
    {'country': 'Gibraltar', 'alpha_two': 'GI', 'alpha_three': 'GIB'},
    {'country': 'Greece', 'alpha_two': 'GR', 'alpha_three': 'GRC'},
    {'country': 'Greenland', 'alpha_two': 'GL', 'alpha_three': 'GRL'},
    {'country': 'Grenada', 'alpha_two': 'GD', 'alpha_three': 'GRD'},
    {'country': 'Guadeloupe', 'alpha_two': 'GP', 'alpha_three': 'GLP'},
    {'country': 'Guam', 'alpha_two': 'GU', 'alpha_three': 'GUM'},
    {'country': 'Guatemala', 'alpha_two': 'GT', 'alpha_three': 'GTM'},
    {'country': 'Guernsey', 'alpha_two': 'GG', 'alpha_three': 'GGY'},
    {'country': 'Guinea', 'alpha_two': 'GN', 'alpha_three': 'GIN'},
    {'country': 'Guinea-Bissau', 'alpha_two': 'GW', 'alpha_three': 'GNB'},
    {'country': 'Guyana', 'alpha_two': 'GY', 'alpha_three': 'GUY'},
    {'country': 'Haiti', 'alpha_two': 'HT', 'alpha_three': 'HTI'},
    {'country': 'Heard Island and McDonald Islands', 'alpha_two': 'HM', 'alpha_three': 'HMD'},
    {'country': 'Holy See (Vatican City State)', 'alpha_two': 'VA', 'alpha_three': 'VAT'},
    {'country': 'Honduras', 'alpha_two': 'HN', 'alpha_three': 'HND'},
    {'country': 'Hong Kong', 'alpha_two': 'HK', 'alpha_three': 'HKG'},
    {'country': 'Hungary', 'alpha_two': 'HU', 'alpha_three': 'HUN'},
    {'country': 'Iceland', 'alpha_two': 'IS', 'alpha_three': 'ISL'},
    {'country': 'India', 'alpha_two': 'IN', 'alpha_three': 'IND'},
    {'country': 'Indonesia', 'alpha_two': 'ID', 'alpha_three': 'IDN'},
    {'country': 'Iran', 'alpha_two': 'Islamic Republic of', 'alpha_three': 'IR'},
    {'country': 'Iraq', 'alpha_two': 'IQ', 'alpha_three': 'IRQ'},
    {'country': 'Ireland', 'alpha_two': 'IE', 'alpha_three': 'IRL'},
    {'country': 'Isle of Man', 'alpha_two': 'IM', 'alpha_three': 'IMN'},
    {'country': 'Israel', 'alpha_two': 'IL', 'alpha_three': 'ISR'},
    {'country': 'Italy', 'alpha_two': 'IT', 'alpha_three': 'ITA'},
    {'country': 'Jamaica', 'alpha_two': 'JM', 'alpha_three': 'JAM'},
    {'country': 'Japan', 'alpha_two': 'JP', 'alpha_three': 'JPN'},
    {'country': 'Jersey', 'alpha_two': 'JE', 'alpha_three': 'JEY'},
    {'country': 'Jordan', 'alpha_two': 'JO', 'alpha_three': 'JOR'},
    {'country': 'Kazakhstan', 'alpha_two': 'KZ', 'alpha_three': 'KAZ'},
    {'country': 'Kenya', 'alpha_two': 'KE', 'alpha_three': 'KEN'},
    {'country': 'Kiribati', 'alpha_two': 'KI', 'alpha_three': 'KIR'},
    {'country': 'Korea', 'alpha_two': "Democratic People's Republic of", 'alpha_three': 'KP'},
    {'country': 'Korea', 'alpha_two': 'Republic of', 'alpha_three': 'KR'},
    {'country': 'South Korea', 'alpha_two': 'KR', 'alpha_three': 'KOR'},
    {'country': 'Kuwait', 'alpha_two': 'KW', 'alpha_three': 'KWT'},
    {'country': 'Kyrgyzstan', 'alpha_two': 'KG', 'alpha_three': 'KGZ'},
    {'country': "Lao People's Democratic Republic", 'alpha_two': 'LA', 'alpha_three': 'LAO'},
    {'country': 'Latvia', 'alpha_two': 'LV', 'alpha_three': 'LVA'},
    {'country': 'Lebanon', 'alpha_two': 'LB', 'alpha_three': 'LBN'},
    {'country': 'Lesotho', 'alpha_two': 'LS', 'alpha_three': 'LSO'},
    {'country': 'Liberia', 'alpha_two': 'LR', 'alpha_three': 'LBR'},
    {'country': 'Libyan Arab Jamahiriya', 'alpha_two': 'LY', 'alpha_three': 'LBY'},
    {'country': 'Libya', 'alpha_two': 'LY', 'alpha_three': 'LBY'},
    {'country': 'Liechtenstein', 'alpha_two': 'LI', 'alpha_three': 'LIE'},
    {'country': 'Lithuania', 'alpha_two': 'LT', 'alpha_three': 'LTU'},
    {'country': 'Luxembourg', 'alpha_two': 'LU', 'alpha_three': 'LUX'},
    {'country': 'Macao', 'alpha_two': 'MO', 'alpha_three': 'MAC'},
    {'country': 'Macedonia', 'alpha_two': 'the former Yugoslav Republic of', 'alpha_three': 'MK'},
    {'country': 'Madagascar', 'alpha_two': 'MG', 'alpha_three': 'MDG'},
    {'country': 'Malawi', 'alpha_two': 'MW', 'alpha_three': 'MWI'},
    {'country': 'Malaysia', 'alpha_two': 'MY', 'alpha_three': 'MYS'},
    {'country': 'Maldives', 'alpha_two': 'MV', 'alpha_three': 'MDV'},
    {'country': 'Mali', 'alpha_two': 'ML', 'alpha_three': 'MLI'},
    {'country': 'Malta', 'alpha_two': 'MT', 'alpha_three': 'MLT'},
    {'country': 'Marshall Islands', 'alpha_two': 'MH', 'alpha_three': 'MHL'},
    {'country': 'Martinique', 'alpha_two': 'MQ', 'alpha_three': 'MTQ'},
    {'country': 'Mauritania', 'alpha_two': 'MR', 'alpha_three': 'MRT'},
    {'country': 'Mauritius', 'alpha_two': 'MU', 'alpha_three': 'MUS'},
    {'country': 'Mayotte', 'alpha_two': 'YT', 'alpha_three': 'MYT'},
    {'country': 'Mexico', 'alpha_two': 'MX', 'alpha_three': 'MEX'},
    {'country': 'Micronesia', 'alpha_two': 'Federated States of', 'alpha_three': 'FM'},
    {'country': 'Moldova', 'alpha_two': 'Republic of', 'alpha_three': 'MD'},
    {'country': 'Monaco', 'alpha_two': 'MC', 'alpha_three': 'MCO'},
    {'country': 'Mongolia', 'alpha_two': 'MN', 'alpha_three': 'MNG'},
    {'country': 'Montenegro', 'alpha_two': 'ME', 'alpha_three': 'MNE'},
    {'country': 'Montserrat', 'alpha_two': 'MS', 'alpha_three': 'MSR'},
    {'country': 'Morocco', 'alpha_two': 'MA', 'alpha_three': 'MAR'},
    {'country': 'Mozambique', 'alpha_two': 'MZ', 'alpha_three': 'MOZ'},
    {'country': 'Myanmar', 'alpha_two': 'MM', 'alpha_three': 'MMR'},
    {'country': 'Burma', 'alpha_two': 'MM', 'alpha_three': 'MMR'},
    {'country': 'Namibia', 'alpha_two': 'NA', 'alpha_three': 'NAM'},
    {'country': 'Nauru', 'alpha_two': 'NR', 'alpha_three': 'NRU'},
    {'country': 'Nepal', 'alpha_two': 'NP', 'alpha_three': 'NPL'},
    {'country': 'Netherlands', 'alpha_two': 'NL', 'alpha_three': 'NLD'},
    {'country': 'Netherlands Antilles', 'alpha_two': 'AN', 'alpha_three': 'ANT'},
    {'country': 'New Caledonia', 'alpha_two': 'NC', 'alpha_three': 'NCL'},
    {'country': 'New Zealand', 'alpha_two': 'NZ', 'alpha_three': 'NZL'},
    {'country': 'Nicaragua', 'alpha_two': 'NI', 'alpha_three': 'NIC'},
    {'country': 'Niger', 'alpha_two': 'NE', 'alpha_three': 'NER'},
    {'country': 'Nigeria', 'alpha_two': 'NG', 'alpha_three': 'NGA'},
    {'country': 'Niue', 'alpha_two': 'NU', 'alpha_three': 'NIU'},
    {'country': 'Norfolk Island', 'alpha_two': 'NF', 'alpha_three': 'NFK'},
    {'country': 'Northern Mariana Islands', 'alpha_two': 'MP', 'alpha_three': 'MNP'},
    {'country': 'Norway', 'alpha_two': 'NO', 'alpha_three': 'NOR'},
    {'country': 'Oman', 'alpha_two': 'OM', 'alpha_three': 'OMN'},
    {'country': 'Pakistan', 'alpha_two': 'PK', 'alpha_three': 'PAK'},
    {'country': 'Palau', 'alpha_two': 'PW', 'alpha_three': 'PLW'},
    {'country': 'Palestinian Territory', 'alpha_two': 'Occupied', 'alpha_three': 'PS'},
    {'country': 'Panama', 'alpha_two': 'PA', 'alpha_three': 'PAN'},
    {'country': 'Papua New Guinea', 'alpha_two': 'PG', 'alpha_three': 'PNG'},
    {'country': 'Paraguay', 'alpha_two': 'PY', 'alpha_three': 'PRY'},
    {'country': 'Peru', 'alpha_two': 'PE', 'alpha_three': 'PER'},
    {'country': 'Philippines', 'alpha_two': 'PH', 'alpha_three': 'PHL'},
    {'country': 'Pitcairn', 'alpha_two': 'PN', 'alpha_three': 'PCN'},
    {'country': 'Poland', 'alpha_two': 'PL', 'alpha_three': 'POL'},
    {'country': 'Portugal', 'alpha_two': 'PT', 'alpha_three': 'PRT'},
    {'country': 'Puerto Rico', 'alpha_two': 'PR', 'alpha_three': 'PRI'},
    {'country': 'Qatar', 'alpha_two': 'QA', 'alpha_three': 'QAT'},
    {'country': 'Réunion', 'alpha_two': 'RE', 'alpha_three': 'REU'},
    {'country': 'Romania', 'alpha_two': 'RO', 'alpha_three': 'ROU'},
    {'country': 'Russian Federation', 'alpha_two': 'RU', 'alpha_three': 'RUS'},
    {'country': 'Russia', 'alpha_two': 'RU', 'alpha_three': 'RUS'},
    {'country': 'Rwanda', 'alpha_two': 'RW', 'alpha_three': 'RWA'},
    {'country': 'Saint Helena', 'alpha_two': 'Ascension and Tristan da Cunha', 'alpha_three': 'SH'},
    {'country': 'Saint Kitts and Nevis', 'alpha_two': 'KN', 'alpha_three': 'KNA'},
    {'country': 'Saint Lucia', 'alpha_two': 'LC', 'alpha_three': 'LCA'},
    {'country': 'Saint Pierre and Miquelon', 'alpha_two': 'PM', 'alpha_three': 'SPM'},
    {'country': 'Saint Vincent and the Grenadines', 'alpha_two': 'VC', 'alpha_three': 'VCT'},
    {'country': 'Saint Vincent & the Grenadines', 'alpha_two': 'VC', 'alpha_three': 'VCT'},
    {'country': 'St. Vincent and the Grenadines', 'alpha_two': 'VC', 'alpha_three': 'VCT'},
    {'country': 'Samoa', 'alpha_two': 'WS', 'alpha_three': 'WSM'},
    {'country': 'San Marino', 'alpha_two': 'SM', 'alpha_three': 'SMR'},
    {'country': 'Sao Tome and Principe', 'alpha_two': 'ST', 'alpha_three': 'STP'},
    {'country': 'Saudi Arabia', 'alpha_two': 'SA', 'alpha_three': 'SAU'},
    {'country': 'Senegal', 'alpha_two': 'SN', 'alpha_three': 'SEN'},
    {'country': 'Serbia', 'alpha_two': 'RS', 'alpha_three': 'SRB'},
    {'country': 'Seychelles', 'alpha_two': 'SC', 'alpha_three': 'SYC'},
    {'country': 'Sierra Leone', 'alpha_two': 'SL', 'alpha_three': 'SLE'},
    {'country': 'Singapore', 'alpha_two': 'SG', 'alpha_three': 'SGP'},
    {'country': 'Slovakia', 'alpha_two': 'SK', 'alpha_three': 'SVK'},
    {'country': 'Slovenia', 'alpha_two': 'SI', 'alpha_three': 'SVN'},
    {'country': 'Solomon Islands', 'alpha_two': 'SB', 'alpha_three': 'SLB'},
    {'country': 'Somalia', 'alpha_two': 'SO', 'alpha_three': 'SOM'},
    {'country': 'South Africa', 'alpha_two': 'ZA', 'alpha_three': 'ZAF'},
    {'country': 'South Georgia and the South Sandwich Islands', 'alpha_two': 'GS', 'alpha_three': 'SGS'},
    {'country': 'South Sudan', 'alpha_two': 'SS', 'alpha_three': 'SSD'},
    {'country': 'Spain', 'alpha_two': 'ES', 'alpha_three': 'ESP'},
    {'country': 'Sri Lanka', 'alpha_two': 'LK', 'alpha_three': 'LKA'},
    {'country': 'Sudan', 'alpha_two': 'SD', 'alpha_three': 'SDN'},
    {'country': 'Suriname', 'alpha_two': 'SR', 'alpha_three': 'SUR'},
    {'country': 'Svalbard and Jan Mayen', 'alpha_two': 'SJ', 'alpha_three': 'SJM'},
    {'country': 'Swaziland', 'alpha_two': 'SZ', 'alpha_three': 'SWZ'},
    {'country': 'Sweden', 'alpha_two': 'SE', 'alpha_three': 'SWE'},
    {'country': 'Switzerland', 'alpha_two': 'CH', 'alpha_three': 'CHE'},
    {'country': 'Syrian Arab Republic', 'alpha_two': 'SY', 'alpha_three': 'SYR'},
    {'country': 'Taiwan', 'alpha_two': 'Province of China', 'alpha_three': 'TW'},
    {'country': 'Taiwan', 'alpha_two': 'TW', 'alpha_three': 'TWN'},
    {'country': 'Tajikistan', 'alpha_two': 'TJ', 'alpha_three': 'TJK'},
    {'country': 'Tanzania', 'alpha_two': 'United Republic of', 'alpha_three': 'TZ'},
    {'country': 'Thailand', 'alpha_two': 'TH', 'alpha_three': 'THA'},
    {'country': 'Timor-Leste', 'alpha_two': 'TL', 'alpha_three': 'TLS'},
    {'country': 'Togo', 'alpha_two': 'TG', 'alpha_three': 'TGO'},
    {'country': 'Tokelau', 'alpha_two': 'TK', 'alpha_three': 'TKL'},
    {'country': 'Tonga', 'alpha_two': 'TO', 'alpha_three': 'TON'},
    {'country': 'Trinidad and Tobago', 'alpha_two': 'TT', 'alpha_three': 'TTO'},
    {'country': 'Tunisia', 'alpha_two': 'TN', 'alpha_three': 'TUN'},
    {'country': 'Turkey', 'alpha_two': 'TR', 'alpha_three': 'TUR'},
    {'country': 'Turkmenistan', 'alpha_two': 'TM', 'alpha_three': 'TKM'},
    {'country': 'Turks and Caicos Islands', 'alpha_two': 'TC', 'alpha_three': 'TCA'},
    {'country': 'Tuvalu', 'alpha_two': 'TV', 'alpha_three': 'TUV'},
    {'country': 'Uganda', 'alpha_two': 'UG', 'alpha_three': 'UGA'},
    {'country': 'Ukraine', 'alpha_two': 'UA', 'alpha_three': 'UKR'},
    {'country': 'United Arab Emirates', 'alpha_two': 'AE', 'alpha_three': 'ARE'},
    {'country': 'United Kingdom', 'alpha_two': 'GB', 'alpha_three': 'GBR'},
    {'country': 'United States', 'alpha_two': 'US', 'alpha_three': 'USA'},
    {'country': 'United States Minor Outlying Islands', 'alpha_two': 'UM', 'alpha_three': 'UMI'},
    {'country': 'Uruguay', 'alpha_two': 'UY', 'alpha_three': 'URY'},
    {'country': 'Uzbekistan', 'alpha_two': 'UZ', 'alpha_three': 'UZB'},
    {'country': 'Vanuatu', 'alpha_two': 'VU', 'alpha_three': 'VUT'},
    {'country': 'Venezuela', 'alpha_two': 'Bolivarian Republic of', 'alpha_three': 'VE'},
    {'country': 'Venezuela', 'alpha_two': 'VE', 'alpha_three': 'VEN'},
    {'country': 'Viet Nam', 'alpha_two': 'VN', 'alpha_three': 'VNM'},
    {'country': 'Vietnam', 'alpha_two': 'VN', 'alpha_three': 'VNM'},
    {'country': 'Virgin Islands', 'alpha_two': 'British', 'alpha_three': 'VG'},
    {'country': 'Virgin Islands', 'alpha_two': 'U.S.', 'alpha_three': 'VI'},
    {'country': 'Wallis and Futuna', 'alpha_two': 'WF', 'alpha_three': 'WLF'},
    {'country': 'Western Sahara', 'alpha_two': 'EH', 'alpha_three': 'ESH'},
    {'country': 'Yemen', 'alpha_two': 'YE', 'alpha_three': 'YEM'},
    {'country': 'Zambia', 'alpha_two': 'ZM', 'alpha_three': 'ZMB'},
    {'country': 'Zimbabwe', 'alpha_two': 'ZW', 'alpha_three': 'ZWE'},
    {'country': 'Unknown', 'alpha_two': 'XX', 'alpha_three': 'XXX'}
];