export const getCountryName = country_three => {
    // get country record
    const country = country_list.filter(record => record['code_three'] === country_three)[0];
    // return alpha two in lower case
    //return country.alpha_two.toLowerCase();
    return country['name'];
}

const country_list = [
    {'name': 'Afghanistan', 'code_three': 'AFG'},
    {'name': 'Aland Islands', 'code_three': 'AXL'},
    {'name': 'Albania', 'code_three': 'ALB'},
    {'name': 'Algeria', 'code_three': 'ALG'},
    {'name': 'American Samoa', 'code_three': 'ASA'},
    {'name': 'Andorra', 'code_three': 'AND'},
    {'name': 'Angola', 'code_three': 'ANG'},
    {'name': 'Anguilla', 'code_three': 'AIA'},
    {'name': 'Antigua and Barbuda', 'code_three': 'ATG'},
    {'name': 'Argentina', 'code_three': 'ARG'},
    {'name': 'Armenia', 'code_three': 'ARM'},
    {'name': 'Artsakh', 'code_three': 'NKR'},
    {'name': 'Aruba', 'code_three': 'ARU'},
    {'name': 'Australia', 'code_three': 'AUS'},
    {'name': 'Austria', 'code_three': 'AUT'},
    {'name': 'Azerbaijan', 'code_three': 'AZE'},
    {'name': 'Bahamas', 'code_three': 'BAH'},
    {'name': 'Bahrain', 'code_three': 'BHR'},
    {'name': 'Bangladesh', 'code_three': 'BAN'},
    {'name': 'Barbados', 'code_three': 'BRB'},
    {'name': 'Basque Country', 'code_three': 'BSQ'},
    {'name': 'Belarus', 'code_three': 'BLR'},
    {'name': 'Belgium', 'code_three': 'BEL'},
    {'name': 'Belize', 'code_three': 'BLZ'},
    {'name': 'Benin', 'code_three': 'BEN'},
    {'name': 'Bermuda', 'code_three': 'BER'},
    {'name': 'Bhutan', 'code_three': 'BHU'},
    {'name': 'Bolivia', 'code_three': 'BOL'},
    {'name': 'Bonaire', 'code_three': 'BOE'},
    {'name': 'Bosnia and Herzegovina', 'code_three': 'BIH'},
    {'name': 'Botswana', 'code_three': 'BOT'},
    {'name': 'Brazil', 'code_three': 'BRA'},
    {'name': 'British Virgin Islands', 'code_three': 'VGB'},
    {'name': 'Brunei', 'code_three': 'BRU'},
    {'name': 'Bulgaria', 'code_three': 'BUL'},
    {'name': 'Burkina Faso', 'code_three': 'BFA'},
    {'name': 'Burundi', 'code_three': 'BDI'},
    {'name': 'Cambodia', 'code_three': 'CAM'},
    {'name': 'Cameroon', 'code_three': 'CMR'},
    {'name': 'Canada', 'code_three': 'CAN'},
    {'name': 'Cape Verde', 'code_three': 'CPV'},
    {'name': 'Catalonia', 'code_three': 'CAT'},
    {'name': 'Cayman Islands', 'code_three': 'CAY'},
    {'name': 'Central African Republic', 'code_three': 'CTA'},
    {'name': 'Chad', 'code_three': 'CHA'},
    {'name': 'Chile', 'code_three': 'CHI'},
    {'name': 'China PR', 'code_three': 'CHN'},
    {'name': 'Chinese Taipei', 'code_three': 'TPE'},
    {'name': 'Colombia', 'code_three': 'COL'},
    {'name': 'Comoros', 'code_three': 'COM'},
    {'name': 'Congo', 'code_three': 'CGO'},
    {'name': 'Cook Islands', 'code_three': 'COK'},
    {'name': 'Costa Rica', 'code_three': 'CRC'},
    {'name': 'Croatia', 'code_three': 'CRO'},
    {'name': 'Cuba', 'code_three': 'CUB'},
    {'name': 'Curaçao', 'code_three': 'CUW'},
    {'name': 'Cyprus', 'code_three': 'CYP'},
    {'name': 'Czech Republic', 'code_three': 'CZE'},
    {'name': 'Denmark', 'code_three': 'DEN'},
    {'name': 'Djibouti', 'code_three': 'DJI'},
    {'name': 'Dominica', 'code_three': 'DMA'},
    {'name': 'Dominican Republic', 'code_three': 'DOM'},
    {'name': 'DR Congo', 'code_three': 'COD'},
    {'name': 'Ecuador', 'code_three': 'ECU'},
    {'name': 'Egypt', 'code_three': 'EGY'},
    {'name': 'El Salvador', 'code_three': 'SLV'},
    {'name': 'England', 'code_three': 'ENG'},
    {'name': 'Equatorial Guinea', 'code_three': 'EQG'},
    {'name': 'Eritrea', 'code_three': 'ERI'},
    {'name': 'Estonia', 'code_three': 'EST'},
    {'name': 'Eswatini', 'code_three': 'SWZ'},
    {'name': 'Ethiopia', 'code_three': 'ETH'},
    {'name': 'F.S. Micronesia', 'code_three': 'FSM'},
    {'name': 'Faroe Islands', 'code_three': 'FRO'},
    {'name': 'Fiji', 'code_three': 'FIJ'},
    {'name': 'Finland', 'code_three': 'FIN'},
    {'name': 'France', 'code_three': 'FRA'},
    {'name': 'French Guiana', 'code_three': 'GUF'},
    {'name': 'Gabon', 'code_three': 'GAB'},
    {'name': 'Galicia', 'code_three': 'GAL'},
    {'name': 'Gambia', 'code_three': 'GAM'},
    {'name': 'Georgia', 'code_three': 'GEO'},
    {'name': 'Germany', 'code_three': 'GER'},
    {'name': 'Ghana', 'code_three': 'GHA'},
    {'name': 'Gibraltar', 'code_three': 'GIB'},
    {'name': 'Great Britain', 'code_three': 'GBR'},
    {'name': 'Greece', 'code_three': 'GRE'},
    {'name': 'Greenland', 'code_three': 'GRL'},
    {'name': 'Grenada', 'code_three': 'GRN'},
    {'name': 'Guadeloupe', 'code_three': 'GLP'},
    {'name': 'Guam', 'code_three': 'GUM'},
    {'name': 'Guatemala', 'code_three': 'GUA'},
    {'name': 'Guinea', 'code_three': 'GUI'},
    {'name': 'Guinea-Bissau', 'code_three': 'GNB'},
    {'name': 'Guyana', 'code_three': 'GUY'},
    {'name': 'Haiti', 'code_three': 'HAI'},
    {'name': 'Honduras', 'code_three': 'HON'},
    {'name': 'Hong Kong', 'code_three': 'HKG'},
    {'name': 'Hungary', 'code_three': 'HUN'},
    {'name': 'Iceland', 'code_three': 'ISL'},
    {'name': 'India', 'code_three': 'IND'},
    {'name': 'Indonesia', 'code_three': 'IDN'},
    {'name': 'Iran', 'code_three': 'IRN'},
    {'name': 'Iraq', 'code_three': 'IRQ'},
    {'name': 'Israel', 'code_three': 'ISR'},
    {'name': 'Italy', 'code_three': 'ITA'},
    {'name': 'Ivory Coast', 'code_three': 'CIV'},
    {'name': 'Jamaica', 'code_three': 'JAM'},
    {'name': 'Japan', 'code_three': 'JPN'},
    {'name': 'Jordan', 'code_three': 'JOR'},
    {'name': 'Kazakhstan', 'code_three': 'KAZ'},
    {'name': 'Kenya', 'code_three': 'KEN'},
    {'name': 'Kiribati', 'code_three': 'KIR'},
    {'name': 'Kosovo', 'code_three': 'KVX'},
    {'name': 'Kuwait', 'code_three': 'KUW'},
    {'name': 'Kyrgyzstan', 'code_three': 'KGZ'},
    {'name': 'Laos', 'code_three': 'LAO'},
    {'name': 'Latvia', 'code_three': 'LVA'},
    {'name': 'Lebanon', 'code_three': 'LBN'},
    {'name': 'Lesotho', 'code_three': 'LES'},
    {'name': 'Liberia', 'code_three': 'LBR'},
    {'name': 'Libya', 'code_three': 'LBY'},
    {'name': 'Liechtenstein', 'code_three': 'LIE'},
    {'name': 'Lithuania', 'code_three': 'LTU'},
    {'name': 'Luxembourg', 'code_three': 'LUX'},
    {'name': 'Macau', 'code_three': 'MAC'},
    {'name': 'Madagascar', 'code_three': 'MAD'},
    {'name': 'Malawi', 'code_three': 'MWI'},
    {'name': 'Malaysia', 'code_three': 'MAS'},
    {'name': 'Maldives', 'code_three': 'MDV'},
    {'name': 'Mali', 'code_three': 'MLI'},
    {'name': 'Malta', 'code_three': 'MLT'},
    {'name': 'Martinique', 'code_three': 'MTQ'},
    {'name': 'Mauritania', 'code_three': 'MTN'},
    {'name': 'Mauritius', 'code_three': 'MRI'},
    {'name': 'Mexico', 'code_three': 'MEX'},
    {'name': 'Moldova', 'code_three': 'MDA'},
    {'name': 'Monaco', 'code_three': 'MON'},
    {'name': 'Mongolia', 'code_three': 'MNG'},
    {'name': 'Montenegro', 'code_three': 'MNE'},
    {'name': 'Montserrat', 'code_three': 'MSR'},
    {'name': 'Morocco', 'code_three': 'MAR'},
    {'name': 'Mozambique', 'code_three': 'MOZ'},
    {'name': 'Myanmar', 'code_three': 'MYA'},
    {'name': 'Namibia', 'code_three': 'NAM'},
    {'name': 'Nepal', 'code_three': 'NEP'},
    {'name': 'Netherlands', 'code_three': 'NED'},
    {'name': 'New Caledonia', 'code_three': 'NCL'},
    {'name': 'New Zealand', 'code_three': 'NZL'},
    {'name': 'Nicaragua', 'code_three': 'NCA'},
    {'name': 'Niger', 'code_three': 'NIG'},
    {'name': 'Nigeria', 'code_three': 'NGA'},
    {'name': 'Niue', 'code_three': 'NIU'},
    {'name': 'North Korea', 'code_three': 'PRK'},
    {'name': 'North Macedonia', 'code_three': 'MKD'},
    {'name': 'Northern Cyprus', 'code_three': 'TRNC'},
    {'name': 'Northern Ireland', 'code_three': 'NIR'},
    {'name': 'Northern Mariana Islands', 'code_three': 'NMI'},
    {'name': 'Norway', 'code_three': 'NOR'},
    {'name': 'Oman', 'code_three': 'OMA'},
    {'name': 'Pakistan', 'code_three': 'PAK'},
    {'name': 'Palau', 'code_three': 'PLW'},
    {'name': 'Palestine', 'code_three': 'PLE'},
    {'name': 'Panama', 'code_three': 'PAN'},
    {'name': 'Papua New Guinea', 'code_three': 'PNG'},
    {'name': 'Paraguay', 'code_three': 'PAR'},
    {'name': 'Peru', 'code_three': 'PER'},
    {'name': 'Philippines', 'code_three': 'PHI'},
    {'name': 'Poland', 'code_three': 'POL'},
    {'name': 'Portugal', 'code_three': 'POR'},
    {'name': 'Puerto Rico', 'code_three': 'PUR'},
    {'name': 'Qatar', 'code_three': 'QAT'},
    {'name': 'Republic of Ireland', 'code_three': 'IRL'},
    {'name': 'Réunion', 'code_three': 'REU'},
    {'name': 'Romania', 'code_three': 'ROU'},
    {'name': 'Russia', 'code_three': 'RUS'},
    {'name': 'Rwanda', 'code_three': 'RWA'},
    {'name': 'Saint Kitts and Nevis', 'code_three': 'SKN'},
    {'name': 'Saint Lucia', 'code_three': 'LCA'},
    {'name': 'Saint Martin', 'code_three': 'SMN'},
    {'name': 'Saint Vincent and the Grenadines', 'code_three': 'VIN'},
    {'name': 'Samoa', 'code_three': 'SAM'},
    {'name': 'San Marino', 'code_three': 'SMR'},
    {'name': 'São Tomé and Príncipe', 'code_three': 'STP'},
    {'name': 'Saudi Arabia', 'code_three': 'KSA'},
    {'name': 'Scotland', 'code_three': 'SCO'},
    {'name': 'Senegal', 'code_three': 'SEN'},
    {'name': 'Serbia', 'code_three': 'SRB'},
    {'name': 'Seychelles', 'code_three': 'SEY'},
    {'name': 'Sierra Leone', 'code_three': 'SLE'},
    {'name': 'Singapore', 'code_three': 'SIN'},
    {'name': 'Sint Maarten', 'code_three': 'SMA'},
    {'name': 'Slovakia', 'code_three': 'SVK'},
    {'name': 'Slovenia', 'code_three': 'SVN'},
    {'name': 'Solomon Islands', 'code_three': 'SOL'},
    {'name': 'Somalia', 'code_three': 'SOM'},
    {'name': 'South Africa', 'code_three': 'RSA'},
    {'name': 'South Korea', 'code_three': 'KOR'},
    {'name': 'South Sudan', 'code_three': 'SSD'},
    {'name': 'Spain', 'code_three': 'ESP'},
    {'name': 'Sri Lanka', 'code_three': 'SRI'},
    {'name': 'Sudan', 'code_three': 'SDN'},
    {'name': 'Suriname', 'code_three': 'SUR'},
    {'name': 'Sweden', 'code_three': 'SWE'},
    {'name': 'Switzerland', 'code_three': 'SUI'},
    {'name': 'Syria', 'code_three': 'SYR'},
    {'name': 'Tahiti', 'code_three': 'TAH'},
    {'name': 'Tajikistan', 'code_three': 'TJK'},
    {'name': 'Tanzania', 'code_three': 'TAN'},
    {'name': 'Thailand', 'code_three': 'THA'},
    {'name': 'Timor-Leste', 'code_three': 'TLS'},
    {'name': 'Togo', 'code_three': 'TOG'},
    {'name': 'Tonga', 'code_three': 'TGA'},
    {'name': 'Trinidad and Tobago', 'code_three': 'TRI'},
    {'name': 'Tunisia', 'code_three': 'TUN'},
    {'name': 'Turkey', 'code_three': 'TUR'},
    {'name': 'Turkmenistan', 'code_three': 'TKM'},
    {'name': 'Turks and Caicos Islands', 'code_three': 'TCA'},
    {'name': 'Tuvalu', 'code_three': 'TUV'},
    {'name': 'U.S. Virgin Islands', 'code_three': 'VIR'},
    {'name': 'Uganda', 'code_three': 'UGA'},
    {'name': 'Ukraine', 'code_three': 'UKR'},
    {'name': 'United Arab Emirates', 'code_three': 'UAE'},
    {'name': 'United States', 'code_three': 'USA'},
    {'name': 'Uruguay', 'code_three': 'URU'},
    {'name': 'Uzbekistan', 'code_three': 'UZB'},
    {'name': 'Vanuatu', 'code_three': 'VAN'},
    {'name': 'Vatican City', 'code_three': 'VAT'},
    {'name': 'Venezuela', 'code_three': 'VEN'},
    {'name': 'Vietnam', 'code_three': 'VIE'},
    {'name': 'Wales', 'code_three': 'WAL'},
    {'name': 'Yemen', 'code_three': 'YEM'},
    {'name': 'Zambia', 'code_three': 'ZAM'},
    {'name': 'Zanzibar', 'code_three': 'ZAN'},
    {'name': 'Zimbabwe', 'code_three': 'ZIM'},
    {'name': 'Unknown', 'code_three': 'XXX'}
];